language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run validate
deploy:
  - provider: npm
    edge: true
    email: 128techadmin@128technology.com
    skip_cleanup: true
    api_key:
      secure: Q7q78WsVCzBrCxkfzJHsvH53YdgocdsZLNwegdI4kPyA7c89UJaxCzWklojdn78TYJgDxKTufRGl3Ox2PUIYJjm7WfumskZyFwK59kLa+17y6+xu4YRYbh2ZqlHhGUOErpnzJJNULYGzOf2zPOQOz/T0ICaBMBcbhQyTaj4zoQQJYWx6tDndyt6dnYQlorXxejVglCDPcXcwx1LQLDkKC69ht4NPlkcS9aw/zoaHZ11qUeeom/bD3tIfYhriLRZ8Ah4XxW1ZU2zpRqug4/Z62QWx1Op8znSBq37zivfaTnDhM14NvotyYH2chbjN1giFBylgiU8FbPgkkgqwxwae9dwuBW+R0rEOFnRSVEGGgALPAG3zGxnRGvtBg+kHKXHm4MdydehtG6pFwZiT+t4ro1gpHXXXoHtNoqGvbcuaxx3xvXZNJoIZb5dXJc0uoDNEIWTwU3A3t4Ez47z41v7Ux5hPKnI2fwFA9WIu4g4j2B+MiiiGYtmPrkxqlK2dsCIzGvfTBBhuaEKM6RUFieCf/bOyZEObR1oukG6MmBNZmHHzmANtO4WL3HUO1mYH/eOFRJ7/w7Xqss27J2DryDu9zM5+tHdBgOUjQw3wS6obPy0uJ5x4RNXhZ/04RcFPAcJuA3Yg4B8WY7jNuPdRmpafkZJaKSz0AaR+6kbphajwYQA=
    on:
      repo: 128technology/yinz
      branch: master
